### ISSUE TITLE
use std::map to store different clients

### ISSUE THREAD

**Issue by ronytigo** [offa/influxdb-cxx#163] opened 2023-01-29 15:27 UTC
```
std::map<std::string, influxdb::InfluxDB*> influx_client_map;
// inserting to map
influx_client_map[bucket] =
influxdb::InfluxDBFactory::Get(host + ":" + port + "?db=" + bucket + " --" + token).get();
// getting client from map
influxdb::InfluxDB* influx_client = influx_client_map[tag->m_bucket];
```
when I call `influx_client->write(...)` I get bad_alloc error.

**Comment by offa** [comment] 2023-01-29 16:06
Your code has undefined behaviour. Please be aware that `InfluxDBFactory::Get()` returns an *`unique_ptr`* – you have to care about it's lifetime.

**Comment by offa** [comment] 2023-01-29 19:01
You have to keep a unique_ptr, otherwise it'll destroy the object it points to.

**Comment by ronytesler** [comment] 2023-01-30 00:50
What is UB?
So how can I get the `influxdb::InfluxDB*`? or how can I use a map with different influx client?
Let's say I have 10 different databases, each with different url and I want a map like <string, influx client>. What should I do?

**Comment by ronytigo** [comment] 2023-01-30 20:45
That's what I tried in the beginning and I get this error:
error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = influxdb::InfluxDB; _Dp = std::default_delete<influxdb::InfluxDB>]’
Because it tries to use the copy constructor I think.
This is my code:
```
std::map<std::string, std::unique_ptr<influxdb::InfluxDB>> influx_client_map;

std::unique_ptr influx_client = influxdb::InfluxDBFactory::Get(url);
influx_client_map.insert("first", influx_client);

std::unique_ptr influx_client = influx_client_map["first"];

```

**Comment by offa** [comment] 2023-01-31 17:30
You can use `[]` operator to avoid the copy:

```cpp
influx_client_map["first"] = influxdb::InfluxDBFactory::Get(url);
```

**Comment by ronytigo** [comment] 2023-01-31 18:02
It's the same. I get the error for the line:
`std::unique_ptr influx_client = influx_client_map["first"];`

**Comment by offa** [comment] 2023-01-31 18:04
Because you can't copy an unique_ptr. It doesn't matter whether you copy it in or out.

**Comment by ronytigo** [comment] 2023-01-31 18:15
So how can I hold different clients and have a map between a string and a client?

**Comment by offa** [comment] 2023-01-31 18:59
You can use a map as shown above. Again, the example above doesn't work because it would create a copy of the unique_ptr in the map. You have to either access the managed object – the client – through the unique_ptr or transfer it out of the map, depending on what you want to do.

At this point however, we have become quite of topic since this is a general C++ programming topic and not related to the influxdb client.

**Comment by ronytigo** [comment] 2023-01-31 20:45
I tried to access the managed object, this was the first example, I got bad_alloc.

**Comment by offa** [comment] 2023-02-01 16:59
Can you provide a minimal compiling example to reproduce the issue? What compiler are you using btw.?

I still can't reproduce the issue. Even putting 1000 entries into a map – with unique keys, each having a new value object. Neither do I get a crash by adding that much entries, nor by accessing each of them.

I might help to execute the unit tests (or the system tests if you can use a test database) to verify the lib works on your system.

**Comment by ronytigo** [comment] 2023-02-01 20:24
The lib works, I see the data in the db. The problem is that I accessed it like this:
`unique_ptr<influxdb::InfluxDB> client = std::move(my_map["first"]);`
and the next time I want to access it again I do `unique_ptr<influxdb::InfluxDB> client = std::move(my_map["first"]);`
and now it's already null.
So what I did is after using the pointer, I ran `my_map["first"] = std::move(client);` and it seems to work.
Is that the correct way of using it?

**Comment by offa** [comment] 2023-02-02 15:52
```cpp
unique_ptr<influxdb::InfluxDB> client = std::move(my_map["first"]);
```
After this line you can no longer use the object in the map as you have transferred ownership to the client unique_ptr.

> Is that the correct way of using it?

It works but I wouldn't suggest it. If you need to do further work on the database you can either use a pointer or reference. In some cases you simply can use `my_map["first"]->write(…)`. Ultimately it depends on your use case and what you want to do. 

It might help to get familiar with unique_ptr and move semantics though.

**Closed by offa** 2023-02-02 15:52 UTC
Labels: question

**Comment by ronytigo** [comment] 2023-02-02 16:33
I tried `my_map["first"]->write(…)` and it didn't work. I also tried to call `.get()` on the InfluxDB::Get() so I can have an InfluxDB* instead of a unique_pointer but that also didn't work.

**Comment by offa** [comment] 2023-02-02 16:40
Wired, both work fine (as they should per C++ standard) on all of my tests.

**Comment by ronytigo** [comment] 2023-02-02 16:56
OK `my_map["first"]->write(…)` does work, I don't know why last time I checked it didn't work, I guess I did something else incorrectly.
Thanks!
